import { ROLES } from "./roles";
import { PERMISSIONS } from "./permissions";

export const ROLE_PERMISSIONS = {

    [ROLES.OWNER]: [

        PERMISSIONS.PRODUCT_VIEW,
        PERMISSIONS.PRODUCT_CREATE,
        PERMISSIONS.PRODUCT_UPDATE,
        PERMISSIONS.PRODUCT_DELETE,

        PERMISSIONS.PLAYLIST_VIEW,
        PERMISSIONS.PLAYLIST_CREATE,
        PERMISSIONS.PLAYLIST_UPDATE,
        PERMISSIONS.PLAYLIST_DELETE,

        PERMISSIONS.HOST_VIEW,
        PERMISSIONS.HOST_CREATE,
        PERMISSIONS.HOST_UPDATE,
        PERMISSIONS.HOST_DELETE,

        PERMISSIONS.BILLING_VIEW,
        PERMISSIONS.BILLING_UPDATE,

        PERMISSIONS.SETTINGS_VIEW,
        PERMISSIONS.SETTINGS_UPDATE,

        PERMISSIONS.ANALYTICS_VIEW,

    ],

};